import type { PresetRules, PresetPolicyName } from '../types/preset.types.ts'

export const presetExtensions = '*.{ts,tsx,mts,cts}'

export const presetPolicyOrder: PresetPolicyName[] = [
  'formatting',
  'layout',
  'imports',
  'banTypes',
  'typeSafety',
  'moduleLayout',
  'serviceModules',
  'naming',
  'comments',
  'wrappers',
  'mutableState',
  'backendRules',
  'tests',
  'schemas',
  'reactRules',
  'effects',
  'routes',
  'forms',
  'memoization',
  'boundaries',
  'clientOwnership',
  'tailwindRules',
  'shadcnRules',
]

export const presetCommonRules: PresetRules = {
  'jsx-a11y/no-noninteractive-tabindex': 'error',
  'no-case-declarations': 'error',
  'no-empty': 'error',
  'no-fallthrough': 'error',
  'no-prototype-builtins': 'error',
  'no-regex-spaces': 'error',
  'array-callback-return': 'error',
  'default-case-last': 'error',
  eqeqeq: 'error',
  'no-alert': 'error',
  'no-constructor-return': 'error',
  'no-else-return': 'error',
  'no-extend-native': 'error',
  'no-extra-bind': 'error',
  'no-extra-label': 'error',
  'no-labels': 'error',
  'no-lone-blocks': 'error',
  'no-new': 'error',
  'no-new-func': 'error',
  'no-new-wrappers': 'error',
  'no-param-reassign': 'error',
  'no-proto': 'error',
  'no-return-assign': 'error',
  'no-script-url': 'error',
  'no-self-compare': 'error',
  'no-sequences': 'error',
  'no-useless-call': 'error',
  'no-useless-concat': 'error',
  'no-useless-return': 'error',
  'no-useless-computed-key': 'error',
  'no-var': 'error',
  'object-shorthand': 'error',
  'prefer-const': 'error',
  'prefer-numeric-literals': 'error',
  'prefer-rest-params': 'error',
  'prefer-spread': 'error',
  'prefer-template': 'error',
  'symbol-description': 'error',
  'no-promise-executor-return': 'error',
  'no-template-curly-in-string': 'error',
  'new-cap': [
    'error',
    {
      capIsNew: false,
    },
  ],
  'no-lonely-if': 'error',
  'no-multi-assign': 'error',
  'no-nested-ternary': 'error',
  'no-unneeded-ternary': 'error',
  'prefer-object-spread': 'error',
  'no-label-var': 'error',
  'no-await-in-loop': 'error',
  curly: 'error',
  'typescript/no-array-constructor': 'error',
  'typescript/no-dynamic-delete': 'error',
  'typescript/no-empty-object-type': 'error',
  'typescript/no-invalid-void-type': 'error',
  'typescript/no-mixed-enums': 'error',
  'typescript/no-namespace': 'error',
  'typescript/no-non-null-asserted-nullish-coalescing': 'error',
  'typescript/no-non-null-assertion': 'error',
  'typescript/no-require-imports': 'error',
  'typescript/no-unnecessary-boolean-literal-compare': 'error',
  'typescript/no-unnecessary-condition': 'error',
  'typescript/no-unnecessary-template-expression': 'error',
  'typescript/no-unnecessary-type-arguments': 'error',
  'typescript/no-unnecessary-type-assertion': 'error',
  'typescript/no-unnecessary-type-constraint': 'error',
  'typescript/no-unsafe-enum-comparison': 'error',
  'typescript/no-unsafe-function-type': 'error',
  'typescript/no-unused-expressions': 'error',
  'no-unused-vars': [
    'error',
    {
      args: 'after-used',
      argsIgnorePattern: '^_',
      ignoreRestSiblings: false,
      vars: 'all',
      varsIgnorePattern: '^_',
    },
  ],
  'typescript/no-useless-constructor': 'error',
  'typescript/prefer-literal-enum-member': 'error',
  'typescript/prefer-promise-reject-errors': 'error',
  'typescript/prefer-reduce-type-parameter': 'error',
  'typescript/prefer-return-this-type': 'error',
  'typescript/restrict-plus-operands': 'error',
  'typescript/return-await': ['error', 'error-handling-correctness-only'],
  'typescript/unbound-method': 'error',
  'typescript/use-unknown-in-catch-callback-variable': 'error',
  'typescript/unified-signatures': 'error',
  'typescript/adjacent-overload-signatures': 'error',
  'typescript/array-type': 'error',
  'typescript/ban-tslint-comment': 'error',
  'typescript/class-literal-property-style': 'error',
  'typescript/consistent-generic-constructors': 'error',
  'typescript/consistent-indexed-object-style': 'error',
  'typescript/consistent-type-assertions': 'error',
  'typescript/consistent-type-definitions': 'error',
  'typescript/consistent-type-imports': [
    'error',
    {
      prefer: 'type-imports',
      disallowTypeAnnotations: true,
      fixStyle: 'separate-type-imports',
    },
  ],
  'typescript/no-confusing-non-null-assertion': 'error',
  'typescript/no-empty-function': 'error',
  'typescript/no-inferrable-types': 'error',
  'typescript/non-nullable-type-assertion-style': 'error',
  'typescript/prefer-find': 'error',
  'typescript/prefer-for-of': 'error',
  'typescript/prefer-function-type': 'error',
  'typescript/prefer-includes': 'error',
  'typescript/prefer-nullish-coalescing': 'error',
  'typescript/prefer-optional-chain': 'error',
  'typescript/prefer-regexp-exec': 'error',
  'typescript/prefer-string-starts-ends-with': 'error',
  'typescript/consistent-type-exports': 'error',
  'typescript/switch-exhaustiveness-check': 'error',
  'typescript/default-param-last': 'error',
  'typescript/no-loop-func': 'error',
  'typescript/no-shadow': 'error',
  'unicorn/prefer-at': 'error',
  'unicorn/prefer-node-protocol': 'error',
  'react-hooks/rules-of-hooks': 'error',
  'react-hooks/exhaustive-deps': 'error',
  'oxc/no-accumulating-spread': 'error',
  '@regru/prefer-early-return/prefer-early-return': [
    'error',
    {
      maximumStatements: 1,
    },
  ],
  'tsdoc/syntax': 'error',
  '@eslint-community/eslint-comments/no-aggregating-enable': 'error',
  '@eslint-community/eslint-comments/no-duplicate-disable': 'error',
  '@eslint-community/eslint-comments/no-unused-enable': 'error',
}

export const presetFormattingRules: PresetRules = {
  'eslint-js/padding-line-between-statements': [
    'error',
    {
      blankLine: 'always',
      prev: ['multiline-const', 'multiline-let'],
      next: '*',
    },
    {
      blankLine: 'always',
      prev: '*',
      next: ['multiline-const', 'multiline-let'],
    },
  ],
  'eslint-js/indent': [
    'error',
    2,
    {
      MemberExpression: 1,
      SwitchCase: 1,
      flatTernaryExpressions: true,
    },
  ],
  'eslint-js/semi': ['error', 'always'],
  'eslint-js/quotes': [
    'error',
    'single',
    {
      avoidEscape: true,
    },
  ],
  'eslint-js/comma-dangle': ['error', 'always-multiline'],
  'eslint-js/no-trailing-spaces': 'error',
  'eslint-js/no-multiple-empty-lines': [
    'error',
    {
      max: 1,
    },
  ],
  'eslint-js/eol-last': ['error', 'always'],
  'eslint-js/no-multi-spaces': 'error',
  'eslint-js/arrow-spacing': 'error',
  'eslint-js/block-spacing': 'error',
  'eslint-js/comma-spacing': [
    'error',
    {
      before: false,
      after: true,
    },
  ],
  'eslint-js/key-spacing': [
    'error',
    {
      beforeColon: false,
      afterColon: true,
    },
  ],
  'eslint-js/keyword-spacing': [
    'error',
    {
      before: true,
      after: true,
    },
  ],
  'eslint-js/object-curly-spacing': ['error', 'always'],
  'eslint-js/semi-spacing': [
    'error',
    {
      before: false,
      after: true,
    },
  ],
  'eslint-js/space-before-blocks': 'error',
  'eslint-js/space-before-function-paren': [
    'error',
    {
      anonymous: 'always',
      named: 'never',
      asyncArrow: 'always',
    },
  ],
  'eslint-js/space-infix-ops': 'error',
  'eslint-js/space-in-parens': ['error', 'never'],
  'eslint-js/template-curly-spacing': ['error', 'never'],
  'eslint-js/rest-spread-spacing': ['error', 'never'],
  'eslint-js/computed-property-spacing': ['error', 'never'],
  'eslint-js/brace-style': [
    'error',
    '1tbs',
    {
      allowSingleLine: false,
    },
  ],
  'eslint-js/arrow-parens': ['error', 'always'],
  'eslint-js/no-extra-semi': 'error',
  'eslint-js/no-floating-decimal': 'error',
  'eslint-js/dot-location': ['error', 'property'],
  'eslint-js/no-whitespace-before-property': 'error',
  'eslint-js/object-curly-newline': [
    'error',
    {
      consistent: true,
    },
  ],
  'eslint-js/object-property-newline': [
    'error',
    {
      allowAllPropertiesOnSameLine: true,
    },
  ],
  'eslint-js/max-len': [
    'error',
    {
      code: 160,
      ignoreUrls: true,
      ignoreStrings: true,
      ignoreTemplateLiterals: true,
      ignoreRegExpLiterals: true,
      ignoreComments: true,
    },
  ],
}

export const presetReactRules: PresetRules = {
  'react/display-name': 'error',
  'react/jsx-no-comment-textnodes': 'error',
  'react/jsx-no-target-blank': 'error',
  'react/no-unknown-property': 'error',
  'react/button-has-type': 'error',
  'react/jsx-boolean-value': 'error',
  'react/jsx-curly-brace-presence': 'error',
  'react/jsx-fragments': 'error',
  'react/jsx-no-useless-fragment': 'error',
  'react/jsx-pascal-case': 'error',
  'react/self-closing-comp': 'error',
  'react-perf/jsx-no-new-object-as-prop': 'off',
  'react-perf/jsx-no-new-array-as-prop': 'off',
  'react-perf/jsx-no-new-function-as-prop': 'off',
  'react-perf/jsx-no-jsx-as-prop': 'off',
  'react-extra/jsx-sort-props': [
    'error',
    {
      ignoreCase: true,
      callbacksLast: true,
      shorthandFirst: true,
      multiline: 'ignore',
      locale: 'auto',
    },
  ],
  'react-extra/jsx-first-prop-new-line': ['error', 'multiline'],
  'react-extra/jsx-max-props-per-line': [
    'error',
    {
      when: 'multiline',
      maximum: 1,
    },
  ],
  'react-extra/jsx-indent-props': ['error', 2],
  'react-extra/jsx-closing-bracket-location': ['error', 'line-aligned'],
  'react-extra/jsx-wrap-multilines': [
    'error',
    {
      declaration: 'parens-new-line',
      assignment: 'parens-new-line',
      return: 'parens-new-line',
      arrow: 'parens-new-line',
      condition: 'parens-new-line',
      logical: 'parens-new-line',
      prop: 'parens-new-line',
    },
  ],
  'react-extra/jsx-curly-newline': ['error', 'consistent'],
  'react-extra/jsx-no-leaked-render': 'error',
  'react-extra/no-unstable-nested-components': 'error',
  'react-extra/function-component-definition': [
    'error',
    {
      namedComponents: 'function-declaration',
    },
  ],
  'react-extra/hook-use-state': 'error',
  'react-extra/no-deprecated': 'error',
  'react-extra/jsx-uses-vars': 'off',
  'react-extra/require-render-return': 'error',
  'svg-jsx/camel-case-colon': 'error',
  'svg-jsx/no-style-string': 'error',
}

export const presetEffectsRules: PresetRules = {
  'react-you-might-not-need-an-effect/no-adjust-state-on-prop-change': 'error',
  'react-you-might-not-need-an-effect/no-reset-all-state-on-prop-change':
    'error',
  'react-you-might-not-need-an-effect/no-event-handler': 'error',
  'react-you-might-not-need-an-effect/no-pass-live-state-to-parent': 'error',
  'react-you-might-not-need-an-effect/no-pass-data-to-parent': 'error',
  'react-you-might-not-need-an-effect/no-initialize-state': 'error',
  'react-you-might-not-need-an-effect/no-chain-state-updates': 'error',
  'react-you-might-not-need-an-effect/no-derived-state': 'error',
}

export const presetTailwindRules = {
  'better-tailwindcss/enforce-canonical-classes': 'error',
  'better-tailwindcss/enforce-consistent-class-order': 'error',
  'better-tailwindcss/enforce-shorthand-classes': 'error',
  'better-tailwindcss/no-conflicting-classes': 'error',
  'better-tailwindcss/no-duplicate-classes': 'error',
  'better-tailwindcss/no-unknown-classes': 'off',
  'better-tailwindcss/no-unnecessary-whitespace': 'error',
  'better-tailwindcss/no-deprecated-classes': 'error',
} satisfies PresetRules

export const presetImportRules: PresetRules = {
  'import/first': 'error',
  'import/no-absolute-path': 'error',
  'import/no-mutable-exports': 'error',
  'import/no-self-import': 'error',
  'import/no-duplicates': 'error',
  'import/no-named-as-default': 'error',
  'import/no-named-as-default-member': 'error',
  'import/consistent-type-specifier-style': 'error',
  'unused-imports/no-unused-imports': 'error',
  'import-extra/no-useless-path-segments': 'error',
  'import-extra/no-relative-packages': 'error',
  'import-extra/newline-after-import': 'error',
  'perfectionist/sort-named-imports': [
    'error',
    {
      type: 'natural',
      ignoreCase: true,
    },
  ],
}

export const presetNamingRules: PresetRules = {
  'unicorn/filename-case': [
    'error',
    {
      case: 'kebabCase',
    },
  ],
}

export const presetTestRules: PresetRules = {
  'jest/expect-expect': 'off',
  'jest/no-conditional-expect': 'off',
  'jest/no-disabled-tests': 'off',
  'jest/no-export': 'off',
  'jest/no-standalone-expect': 'off',
  'jest/require-to-throw-message': 'off',
  'vitest/no-standalone-expect': [
    'error',
    {
      additionalTestBlockFunctions: ['test'],
    },
  ],
  'vitest/expect-expect': [
    'error',
    {
      additionalTestBlockFunctions: ['test'],
    },
  ],
  'vitest/require-mock-type-parameters': 'error',
}

export const presetExportPrefix = {
  stem: 'before-first-dot',
  trailingRoles: ['constants', 'utils', 'handler', 'service', 'types'],
  roleSeparators: ['.', '-'],
  normalize: 'remove-separators',
  allowPattern: '^(make[A-Z]|\\*$)',
}

export const presetGeneratedFiles = [
  '**/*.generated.*',
  '**/*.gen.*',
  '**/*.d.ts',
  '**/routes.tree.ts',
  '**/routeTree.gen.ts',
  '**/paraglide/**',
]
